#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

infra:
  - changed-files:
    - any-glob-to-any-file: [
        ".github/**",
        ".asf.yaml",
        ".rat-excludes",
        ".gitattributes",
        ".gitignore",
        ".gitmodules"
      ]

build:
  - changed-files:
    - any-glob-to-any-file: [
        "build/**",
        "**/*pom.xml",
        "Cargo.toml",
        "Cargo.lock",
        "auron-build.sh",
        "rust-toolchain.toml",
        "rustfmt.toml",
        "scalafix.conf",
        "scalafmt.conf"
      ]

documentation:
  - changed-files:
    - any-glob-to-any-file: [
        "**/*.md",
        "LICENSE"
      ]

core:
  - changed-files:
    - any-glob-to-any-file: [
        "auron-core/**"
      ]

common:
  - changed-files:
    - any-glob-to-any-file: [
        "common/**"
      ]

native:
  - changed-files:
    - any-glob-to-any-file: [
        "native-engine/**"
      ]

hadoop:
  - changed-files:
    - any-glob-to-any-file: [
        "hadoop-shim/**"
      ]

spark:
  - changed-files:
    - any-glob-to-any-file: [
        "spark-extension/**",
        "spark-extension-shims-spark/**",
        "spark-version-annotation-macros/**"
      ]

spark-ui:
  - changed-files:
    - any-glob-to-any-file: [
        "auron-spark-ui/**"
      ]

spark-tests:
  - changed-files:
    - any-glob-to-any-file: [
        "auron-spark-tests/**"
      ]

flink:
  - changed-files:
    - any-glob-to-any-file: [
        "auron-flink-extension/**"
      ]

thirdparty-celeborn:
  - changed-files:
    - any-glob-to-any-file: [
        "thirdparty/auron-celeborn-*/**"
      ]

thirdparty-uniffle:
  - changed-files:
    - any-glob-to-any-file: [
        "thirdparty/auron-uniffle/**"
      ]

thirdparty-paimon:
  - changed-files:
    - any-glob-to-any-file: [
        "thirdparty/auron-paimon/**"
      ]

thirdparty-iceberg:
  - changed-files:
    - any-glob-to-any-file: [
        "thirdparty/auron-iceberg/**"
      ]

dev-tools:
  - changed-files:
    - any-glob-to-any-file: [
        "dev/**",
        ".idea/**"
      ]

benchmark:
  - changed-files:
    - any-glob-to-any-file: [
        "benchmark-results/**"
      ]
